"use client";

import React from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { motion } from "framer-motion";

export default function TermsConditionsPage() {
  return (
    <>
      <Navbar />

      <section className="relative w-full bg-black text-white py-28 md:py-36 flex justify-center overflow-hidden">

        {/* Dark Overlay */}
        <div className="absolute inset-0 bg-gradient-to-b from-black/40 via-black/70 to-black/90"></div>

        {/* Orange Glow */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 w-[650px] h-[650px] bg-orange-500/25 blur-[150px] rounded-full opacity-70"></div>

        {/* Hero Content */}
        <motion.div
          initial={{ opacity: 0, y: 45 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.9 }}
          className="relative max-w-4xl mx-auto px-6 text-center"
        >
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-wide drop-shadow-xl">
            Terms & Conditions
          </h1>

          {/* underline animation */}
          <motion.div
            initial={{ width: 0 }}
            animate={{ width: 250 }}
            transition={{ duration: 0.7, delay: 0.3 }}
            className="h-[4px] bg-gradient-to-r from-orange-400 to-orange-600 rounded-full mx-auto mt-4 shadow-lg"
          />

          <p className="mt-6 text-lg md:text-xl text-orange-100 max-w-2xl mx-auto leading-relaxed">
            Please read these Terms & Conditions carefully before using our website.
          </p>
        </motion.div>
      </section>

      {/* =============================== */}
      {/*   MAIN CONTENT SECTION          */}
      {/* =============================== */}
      <section className="w-full mt-10 flex justify-center bg-white md:py-15">
        <div className="w-full max-w-[100%] px-4 sm:px-6 md:px-10 lg:px-14 xl:px-20">

          {/* Content Card */}
          <div className="bg-white shadow-[0_10px_30px_rgba(0,0,0,0.08)] rounded-2xl p-6 sm:p-10 md:p-12 space-y-12 border border-orange-100">

            {/* INTRO TEXT */}
            <motion.div
              initial={{ opacity: 0, y: 25 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              viewport={{ once: true }}
              className="space-y-6"
            >
              <p>
                This document is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder.
                This electronic record is generated by a computer system and does not require any physical or digital signatures.
              </p>

              <p>
                This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology
                (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and
                Terms of Use for access or usage of the domain name https://agarwalrabdiwala.in/.
              </p>

              <p>
                The Platform is owned and operated by Aagarwal Rabdiwala, a Proprietorship Firm, having its principal place of
                business at Shop No. 16, Railway Taxi Parking, Welcome Home, Namaste, Abu Road, Rajasthan – 307026.
              </p>

              <p className="font-semibold text-gray-900">
                By accessing, browsing, or otherwise using this Platform, you agree to be bound by these Terms & Conditions
                along with our Privacy Policy and Return & Refund Policy.
              </p>
            </motion.div>

            {/* SECTION BY SECTION TERMS */}
            {[
              {
                title: "1. User Eligibility",
                points: [
                  "1.1 The user must be capable of entering into a legally binding contract under Indian law.",
                  "1.2 By using this Platform, you represent that you are legally competent to place orders."
                ]
              },
              {
                title: "2. Nature of Services",
                points: [
                  "2.1 We provide online food ordering and restaurant services.",
                  "2.2 All food images displayed are for illustration purposes only and actual presentation may vary.",
                  "2.3 Delivery time is an estimate and not a guaranteed service time."
                ]
              },
              {
                title: "3. User Account & Information",
                points: [
                  "3.1 You agree to provide true, accurate, and complete information while placing orders.",
                  "3.2 You are responsible for maintaining the confidentiality of your order and contact details.",
                  "3.3 We shall not be liable for any loss caused due to incorrect information provided by the customer."
                ]
              },
              {
                title: "4. Pricing & Payments",
                points: [
                  "4.1 All prices are displayed in Indian Rupees (INR).",
                  "4.2 Prices may change at any time without prior notice.",
                  "4.3 Payments can be made through UPI, Debit Card, Credit Card, Net Banking, or any other available method on the Platform.",
                  "4.4 We use secure third-party payment gateways and do not store any card, UPI, or banking information on our servers."
                ]
              },
              {
                title: "5. Order Confirmation & Cancellation",
                points: [
                  "5.1 Orders are confirmed only after successful payment.",
                  "5.2 Orders once confirmed cannot be cancelled after food preparation has started.",
                  "5.3 We reserve the right to cancel any order due to non-availability of items, technical issues, or operational reasons."
                ]
              },
              {
                title: "6. Delivery Policy",
                points: [
                  "6.1 Delivery timelines are approximate and may vary due to traffic, weather, or operational conditions.",
                  "6.2 Delays caused due to third-party delivery partners are beyond our direct control.",
                  "6.3 The risk of food passes to the customer upon successful delivery."
                ]
              },
              {
                title: "7. Food Quality, Allergens & Safety",
                points: [
                  "7.1 We take all reasonable care to prepare hygienic and quality food.",
                  "7.2 Some food items may contain allergens such as milk, nuts, gluten, or spices.",
                  "7.3 Customers with food allergies must exercise discretion before ordering.",
                  "7.4 We shall not be responsible for any allergic reactions unless caused by gross negligence from our side."
                ]
              },
              {
                title: "8. Intellectual Property Rights",
                points: [
                  "8.1 All content on this Platform including logo, design, images, and text are the property of Aagarwal Rabdiwala.",
                  "8.2 Unauthorized use, copying, or reproduction is strictly prohibited."
                ]
              },
              {
                title: "9. Prohibited Activities",
                points: [
                  "9.1 Users shall not use the Platform for unlawful purposes.",
                  "9.2 Users shall not post false reviews or misleading information.",
                  "9.3 Users shall not attempt to hack, manipulate, or misuse the website.",
                  "9.4 Users shall not violate any applicable Indian law."
                ]
              },
              {
                title: "10. Limitation of Liability",
                points: [
                  "10.1 Our total liability shall not exceed the value of the order placed by the customer.",
                  "10.2 We shall not be liable for any indirect, incidental, special, or consequential damages."
                ]
              },
              {
                title: "11. Force Majeure",
                points: [
                  "11.1 We shall not be held liable for any failure or delay in performance due to events beyond our reasonable control."
                ]
              },
              {
                title: "12. Third-Party Links",
                points: [
                  "12.1 The Platform may contain links to third-party websites.",
                  "12.2 We are not responsible for the content, policies, or practices of such third-party websites."
                ]
              },
              {
                title: "13. Indemnification",
                points: [
                  "13.1 You agree to indemnify and hold harmless Aagarwal Rabdiwala from any claims, losses, damages, or liabilities arising due to your misuse of the Platform."
                ]
              },
              {
                title: "14. Modifications to Terms",
                points: [
                  "14.1 We reserve the right to modify or update these Terms & Conditions at any time without prior notice.",
                  "14.2 Continued use after changes constitutes acceptance."
                ]
              },
              {
                title: "15. Governing Law & Jurisdiction",
                points: [
                  "15.1 These Terms shall be governed in accordance with the laws of India.",
                  "15.2 All disputes shall be subject to the exclusive jurisdiction of the courts of Abu Road, Rajasthan."
                ]
              },
              {
                title: "16. Contact Information",
                points: [
                  "16.1 For any queries, complaints, or legal notices, contact us at info@agarwalrabdiwala.in"
                ]
              }
            ].map((section, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 25 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.1 * index }}
                viewport={{ once: true }}
                className="space-y-3"
              >
                <h3 className="text-xl font-bold text-orange-600">{section.title}</h3>
                <ul className="list-disc pl-6 space-y-2">
                  {section.points.map((p, i) => (
                    <li key={i}>{p}</li>
                  ))}
                </ul>
              </motion.div>
            ))}

          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}
